# Generated by Django 4.1.3 on 2023-02-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featureproducts',
            name='ratirng',
        ),
        migrations.AddField(
            model_name='featureproducts',
            name='image',
            field=models.ImageField(null=True, upload_to='featureproducts/'),
        ),
    ]
