# Generated by Django 4.1.3 on 2023-02-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0002_remove_featureproducts_ratirng_featureproducts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='proproducts/')),
                ('name', models.TextField()),
                ('value', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
